Repository wearecoarmot/crawling-ui, pull requests merged in 2020-06, with the labels that each got.

#26 ci/cd: Add docker deploy
  .dockerignore
  Dockerfile
  README.md
  bin/run.sh
  requirements.txt
  server/crawling/views.py
  server/management/commands/createadmin.py
  uwsgi.ini.template
Labels: dependencies

#25 feat: add login event dispatcher
  client/src/components/App.tsx
  client/src/components/Routes/index.ts
  client/src/hooks/useAuthUser.ts
  client/src/hooks/useSignIn.ts
  client/src/lib/store.ts
  client/src/models/user/index.ts
  client/src/utils/apiCall.ts
Labels: Feature

#28 feat: Add crawling setting api
  server/crawling/api.py
  server/crawling/extensions/authentication.py
  server/crawling/models.py
  server/crawling/serializers.py
  server/crawling/urls.py
  server/crawling/views.py
Labels: Feature

#29 refactor: some code refactoring.
  server/crawling/api.py
  server/crawling/extensions/authentication.py
  server/crawling/models.py
  server/crawling/serializers.py
  server/crawling/urls.py
Labels: refactor
